//@version=6
indicator("mss-class", overlay = true)

type ZZ
    array<float> y
    array<int>   d

type mss
    int dir

var mss MSS = mss.new(0)

var aZZ = ZZ.new(array.from(1.0, 2.0, 3.0), array.from(1, 1, 1))

method draw(int left, color col) =>
    iH = aZZ.d.get(2) == 1 ? 2 : 1
    switch
        close > aZZ.y.get(iH) and aZZ.d.get(iH) == 1 and MSS.dir < 1 =>
            MSS.dir := 1
            label.new(bar_index, high, "MSS")
        close < 0 =>
            label.new(bar_index, low, "no")
draw(1, color.red)
